import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { PageHero } from '../components/UI';
import { siteData } from '../config/siteData';
export function Legal(_a) {
    var type = _a.type;
    var privacy = type === 'privacy';
    var sections = siteData.legal[type];
    return _jsxs(_Fragment, { children: [_jsx(PageHero, { code: privacy ? 'PRIVACY POLICY' : 'TERMS OF USE', index: privacy ? 'P–01' : 'T–01', title: privacy ? 'プライバシーポリシー' : '利用規約', lead: privacy ? 'お預かりする情報を適切に管理し、信頼に応えるための基本方針です。' : '当サイトおよび当社サービスを安心してご利用いただくための条件を定めています。' }), _jsxs("section", { className: "legal-layout section-pad", children: [_jsxs("aside", { children: [_jsx("span", { children: "DOCUMENT INDEX" }), sections.map(function (s, i) { return _jsxs("a", { href: "#legal-".concat(i + 1), children: [_jsxs("b", { children: ["0", i + 1] }), s.title] }, s.title); })] }), _jsxs("div", { className: "legal-content", children: [_jsxs("div", { className: "legal-meta", children: [_jsx("span", { children: "\u5236\u5B9A\u65E5\uFF1A2024\u5E744\u67081\u65E5" }), _jsx("span", { children: "\u6700\u7D42\u6539\u5B9A\uFF1A2026\u5E744\u67081\u65E5" })] }), _jsxs("p", { className: "legal-intro", children: [siteData.company.name, "\uFF08\u4EE5\u4E0B\u300C\u5F53\u793E\u300D\uFF09\u306F\u3001", privacy ? '個人情報およびプロジェクトに関わる情報の重要性を認識し、次のとおり取り扱います。' : '当社が運営するウェブサイトおよび提供する情報の利用について、次のとおり定めます。'] }), sections.map(function (section, i) { return _jsxs("article", { id: "legal-".concat(i + 1), children: [_jsxs("span", { children: ["ARTICLE / 0", i + 1] }), _jsx("h2", { children: section.title }), _jsx("p", { children: section.text }), section.title.includes('お問い合わせ') && _jsxs("div", { className: "legal-contact", children: [_jsx("b", { children: siteData.company.name }), _jsx("span", { children: siteData.company.address }), _jsx("a", { href: "mailto:".concat(siteData.company.email), children: siteData.company.email }), _jsx("span", { children: siteData.company.hours })] })] }, section.title); })] })] })] });
}
